apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jira-metrics.fullname" . }}
  labels:
    {{- include "jira-metrics.labels" . | nindent 4 }}
data:
  config.yaml: |
    server: acme.atlassian.net
    interval_seconds: 600
    boards: []
    queues: []
    metrics: []
