server: acme.atlassian.net
interval_seconds: 600
queues:
  -
    name: ACMESD
    time_zone: 'UTC'
boards:
  -
    name: ACME
    in_progress_labels: '"in progress","pending close"'
    in_preparation_labels: '"backlog","selected for development"'
    business_as_usual_epics: '"business as usual","tech debt","incident"'
metrics:
  -
    query: 'project = ACME AND status changed to "Done" after -1d'
    metric_name: devops_board_completed_1d
    metric_type: gauge
    metric_help: 'DevOps tickets completed'
