{
 "title": "Jira Service Desk",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Queue", "query": "acme" }
  ]
 },
 "panels": [
  {
   "title": "Tickets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(jira_metrics_queue_new_tickets_1d{queue=\"$Queue\"})",
     "legendFormat": "new (1d)"
    },
    {
     "expr": "max(jira_metrics_queue_resolved_tickets_1d{queue=\"$Queue\"})",
     "legendFormat": "resolved (1d)"
    },
    {
     "expr": "max(jira_metrics_queue_open_tickets{queue=\"$Queue\"})",
     "legendFormat": "open"
    },
    {
     "expr": "max(jira_metrics_queue_unassigned_tickets{queue=\"$Queue\"})",
     "legendFormat": "unassigned"
    }
   ]
  },
  {
   "title": "Open tickets week on week",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(jira_metrics_queue_open_tickets{queue=\"$Queue\"}[1d])) - max(max_over_time(jira_metrics_queue_open_tickets{queue=\"$Queue\"}[1d] offset 1w))"
    }
   ]
  },
  {
   "title": "Open tickets now",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(jira_metrics_queue_open_tickets{queue=\"$Queue\"})"
    }
   ]
  },
  {
   "title": "Customer satisfaction",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jira_metrics_queue_satisfaction_scores_1d{queue=\"$Queue\", score=\"5\"})",
     "legendFormat": "5"
    },
    {
     "expr": "max(jira_metrics_queue_satisfaction_scores_1d{queue=\"$Queue\", score=\"4\"})",
     "legendFormat": "4"
    },
    {
     "expr": "max(jira_metrics_queue_satisfaction_scores_1d{queue=\"$Queue\", score=\"3\"})",
     "legendFormat": "3"
    },
    {
     "expr": "max(jira_metrics_queue_satisfaction_scores_1d{queue=\"$Queue\", score=\"2\"})",
     "legendFormat": "2"
    },
    {
     "expr": "max(jira_metrics_queue_satisfaction_scores_1d{queue=\"$Queue\", score=\"1\"})",
     "legendFormat": "1"
    },
    {
     "expr": "avg(avg_over_time(jira_metrics_queue_average_satisfaction_scores_1d{queue=\"$Queue\"}[2w]))",
     "legendFormat": "average score (2w)"
    }
   ]
  },
  {
   "title": "Customer satisfaction (2w) week on week",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(jira_metrics_queue_average_satisfaction_scores_1d{queue=\"$Queue\"}[2w]))-avg(avg_over_time(jira_metrics_queue_average_satisfaction_scores_1d{queue=\"$Queue\"}[2w] offset 1w))"
    }
   ]
  },
  {
   "title": "Customer satisfaction (2w)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(jira_metrics_queue_average_satisfaction_scores_1d{queue=\"$Queue\"}[2w]))",
     "legendFormat": "average over 2w"
    }
   ]
  },
  {
   "title": "Tickets outside SLA by reporter",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (reporter) (max_over_time(jira_metrics_queue_open_tickets_outside_sla_reporter_total{queue=\"$Queue\"}[10m]))",
     "legendFormat": "{{reporter}}"
    }
   ]
  },
  {
   "title": "SLA",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(jira_metrics_queue_open_tickets_within_sla{queue=\"$Queue\"}[1d]))",
     "legendFormat": "open tickets within SLA"
    },
    {
     "expr": "max(max_over_time(jira_metrics_queue_open_tickets_outside_sla{queue=\"$Queue\"}[1d]))",
     "legendFormat": "open tickets outside SLA"
    }
   ]
  }
 ]
}