---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/gocityengineering/jira-metrics/schema/schema.json
"$defs":
  board:
    type: object
    properties:
      name:
        type: string
      in_progress_labels:
        type: string
      in_preparation_labels:
        type: string
      business_as_usual_epics:
        type: string
      iteration_length_weeks:
        type: number
    required:
      - name
      - iteration_length_weeks
      - in_progress_labels
      - in_preparation_labels
  queue:
    type: object
    properties:
      name:
        type: string
      time_zone:
        type: string
    required:
      - name
  metric:
    type: object
    properties:
      query:
        type: string
      metric_name:
        type: string
      metric_type:
        type: string
        enum:
          - counter
          - gauge
          - histogram
      metric_help:
        type: string
    required:
      - query
      - metric_name
      - metric_type
title: "jira-metrics schema"
type: object
properties:
  server:
    type: string
  interval_seconds:
    type: number
    minimum: 60
  queues:
    type: array
    items:
      "$ref": "#/$defs/queue"
  metrics:
    type: array
    items:
      "$ref": "#/$defs/metric"
required:
  - server
